logging:
  config: src/main/resources/logback-dev-local.xml

redis:
  host: localhost
  port: 6379
  sslEnabled: false

bankid:
  baseUrl: "https://appapi2.test.bankid.com"
  keyStoreCertificate: |
    -----BEGIN CERTIFICATE-----
    MIIEyjCCArKgAwIBAgIIG8/maByOzV4wDQYJKoZIhvcNAQELBQAwcTELMAkGA1UE
    BhMCU0UxHTAbBgNVBAoMFFRlc3RiYW5rIEEgQUIgKHB1YmwpMRUwEwYDVQQFEwwx
    MTExMTExMTExMTExLDAqBgNVBAMMI1Rlc3RiYW5rIEEgUlAgQ0EgdjEgZm9yIEJh
    bmtJRCBUZXN0MB4XDTI0MDcwMjIyMDAwMFoXDTI5MDUyODIxNTk1OVowcjELMAkG
    A1UEBhMCU0UxHTAbBgNVBAoMFFRlc3RiYW5rIEEgQUIgKHB1YmwpMRMwEQYDVQQF
    Ewo1NTY2MzA0OTI4MRcwFQYDVQQpDA5UZXN0IGF2IEJhbmtJRDEWMBQGA1UEAwwN
    RlAgVGVzdGNlcnQgNTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANwG
    Te3TokhAIefirshdT4vGAhoVLi04zgizezOWTbGp7ll6Jj41VFFg2AnmwajhvIO4
    zxQVgDeHaalTSbknpXQK5kBNwLYHxwfQvQ80Qi/w5lq88WUSbF9XKeAkiOlePOvR
    iW2y+dUATKKL1HwFrMDnILhm2UXMI4eNLRj/j3nkC75hZWn0XlrQiJgeXpRPhP22
    Fo8LdnV0VowHhosZtxt3rbAjsD/If854GRDusIM9wiR0tWiYYGlPNjoRqoHFqDD3
    QLUJgKEQXdqCZmM2+QY0m/bAc++TUJpdPsqetGHx9NhtAb0oF0NKWBkiBgNiZ2xb
    lw17vq+ZSK2AbJPOUOECAwEAAaNlMGMwEQYDVR0gBAowCDAGBgQqAwQFMA4GA1Ud
    DwEB/wQEAwIHgDAfBgNVHSMEGDAWgBTiuVUIvGKgRjldgAxQSpIBy0zvizAdBgNV
    HQ4EFgQUgZHajGxfxKgmJv9TPTr+SMh51X4wDQYJKoZIhvcNAQELBQADggIBACXY
    y4NregbhFckEEJG7E7cTjSDXWrwCbZ4SToxa0JdYMEBoy/FkMi+UVcWBpTLHOvpu
    GSBCv9vpAKYOqclt9jAa0T/mLSb7R5Zm0YVU1LeP4sYJsxauoPyA9wc49rb64qk+
    vGkzZD8YV/Jsb/SbMM3JujFCRLVedHtonY+8xFBec/3SrTVcys8KO897WwRU/5UN
    dOnJCtp7e6lSOzFIsvutoaNIsEZq7kVDikQ3EgXsB0Cxol4/CLTGLae0znzWRAxn
    2pAusNmzInXCjTx57o4+KT5yhjqNIm9ra9XKqGBEqEayFOb2XMD59DelhXb6sX87
    H1yrtMSsKEginq0WZ7BBdZ57BuNA/X8YIKMT0UATA5zoAH+QEGXe2fjfPsvYx5Y6
    D7y2i9GgfyLXbToxMufYnU9MtZuV6ZjW0E32+NRJvtkNVziDHH6/eNx32LLIP0X5
    +J6Ge2gLRnYT3hkKZKxtwR5TEoDCMjvmXTFQifdSjYC0hOn9oLXnjg2ZtQremCym
    3emqINt7LXTXb6qSscD5ZsTAkDqJ5WVgPLMimf8iHhvtTLvQE9b8c+FH6o1qzvV2
    YnzfYGANQU2VUwN3jR8IfIAw/4kwgDURQQkgoqEq1JFowv7L2h//of5dOO7SCHuv
    gH7GxzJbDS4wssRFBHZGpVgK6ZjyPmfemU/MuEnm
    -----END CERTIFICATE-----
  keyStorePrivateKey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDcBk3t06JIQCHn
    4q7IXU+LxgIaFS4tOM4Is3szlk2xqe5ZeiY+NVRRYNgJ5sGo4byDuM8UFYA3h2mp
    U0m5J6V0CuZATcC2B8cH0L0PNEIv8OZavPFlEmxfVyngJIjpXjzr0YltsvnVAEyi
    i9R8BazA5yC4ZtlFzCOHjS0Y/4955Au+YWVp9F5a0IiYHl6UT4T9thaPC3Z1dFaM
    B4aLGbcbd62wI7A/yH/OeBkQ7rCDPcIkdLVomGBpTzY6EaqBxagw90C1CYChEF3a
    gmZjNvkGNJv2wHPvk1CaXT7KnrRh8fTYbQG9KBdDSlgZIgYDYmdsW5cNe76vmUit
    gGyTzlDhAgMBAAECggEAa/x4IOJ+wmEfgvShfds2IE6lV3HPwQghLuoP7Ii3Rxw0
    zBuES4HXCT2zqmBj6eQopql8kMngrOA7/ovPIh2QObzjtumyTGTSzUYolB684VSl
    aiFThJyfLcfU2Jp1y7uhwMeNYJa3wU+tTRW9ysTqPZ7yUy6/Ml93jJ7AZIWBQHvA
    RKEA3CYzHfRYyOPHn+KmbWQt4+hj9Iu+BIwj66Swqiww0ADVudEXCIZfoo8Aufd7
    uzQUaKf7KFB50ILDLv7lWd4NPptgCQQMtkm1oGqRnRPmz34SUuJAzDJ1K1TYJuCP
    EbSMAaeEftEyIbWob8/HPAvbtCEv991KdGi/enjHwQKBgQDskwM20EBTEV+ujyw5
    gJV/UnxBAvc/UW4qtqzqophsSnZZrLzbC52OuLq4lPwv4BkgPhn9pFdTWwm0J07n
    QA30JB8WG2pyKMhrCdyiRj0RBoJmeqElMEzJWQcvp6eTUGyqhgTDB1B+kEFrGHob
    Q0XbcjU7oiJWE4+D9SSCjTI7WQKBgQDuF2eX9b2BUzPpeTPZlL0+N4me2j3fqg4w
    eqkKdb1rdQxqReCz3dCBWBs2NvQ0FIx1oGmaq7apfJ4TC76OC4Y+WtzmrldtwF1c
    OpHqxt3bzvmoTDXVOufJktuXd6H25WgMrXoJGN8Rme1Cxuxc5u8BV2VzJSTlBgqg
    HojZ8mx4yQKBgQCLhYyAuEMnenien2uqog4JICGNyez9l83MPR4v5yLTwvqXmotq
    +Ce882+TyrIMnjLTVCzJ7TFfRLKtX/1l3t4b3W3EAPk/SJQipJdN0PTU5KzlOW9u
    WlT+7pWRYmQvOmBMFWwbhWXQrs0WF0J0b7F0YZ/Jgq6Ta0fZwCr/H7y/SQKBgCS1
    9SIoIN0k8BcqugTtezRxqcWVjv7CoMd20kOrndZIyO5F8fyp0fFvnVqBpKu3E2U7
    o6zWlyaQ8WqsX+hU/JD2v6LN9OsWQw7qdP9HRIQU6Me7YH2NRJn/C97R8mY4Pw/d
    W7i1Xge/vSaTt3Qno2iIijrz2jl58f94Vc+NIo6JAoGBAMeJlDQ0paM8Zday1pnG
    FnF5MhcWTVNZxYhDXO12rTLtj05z7PCTDYhHl2X3ICrTBBiJQdGelhjpx6xCAXU7
    OxHLxDwIKBqCb0HqvoEiQuhjLjg7HyHDi6w+CAE4tWakPJZYyV1aVIZWaE/PRbla
    KoQXAAs3i65s8WpO2DEzotFN
    -----END PRIVATE KEY-----
  trustStore: |
    -----BEGIN CERTIFICATE-----
    MIIF0DCCA7igAwIBAgIIIhYaxu4khgAwDQYJKoZIhvcNAQENBQAwbDEkMCIGA1UE
    CgwbRmluYW5zaWVsbCBJRC1UZWtuaWsgQklEIEFCMRowGAYDVQQLDBFJbmZyYXN0
    cnVjdHVyZSBDQTEoMCYGA1UEAwwfVGVzdCBCYW5rSUQgU1NMIFJvb3QgQ0EgdjEg
    VGVzdDAeFw0xNDExMjExMjM5MzFaFw0zNDEyMzExMjM5MzFaMGwxJDAiBgNVBAoM
    G0ZpbmFuc2llbGwgSUQtVGVrbmlrIEJJRCBBQjEaMBgGA1UECwwRSW5mcmFzdHJ1
    Y3R1cmUgQ0ExKDAmBgNVBAMMH1Rlc3QgQmFua0lEIFNTTCBSb290IENBIHYxIFRl
    c3QwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCAKWsJc/kV/0434d+S
    qn19mIr85RZ/PgRFaUplSrnhuzAmaXihPLCEsd3Mh/YErygcxhQ/MAzi5OZ/anfu
    WSCwceRlQINtvlRPdMoeZtu29FsntK1Z5r2SYNdFwbRFb8WN9FsU0KvC5zVnuDMg
    s5dUZwTmdzX5ZdLP7pdgB3zhTnra5ORtkiWiUxJVev9keRgAo00ZHIRJ+xTfiSPd
    Jc314maigVRQZdGKSyQcQMTWi1YLwd2zwOacNxleYf8xqKgkZsmkrc4Dp2mR5Pkr
    nnKB6A7sAOSNatua7M86EgcGi9AaEyaRMkYJImbBfzaNlaBPyMSvwmBZzp2xKc9O
    D3U06ogV6CJjJL7hSuVc5x/2H04d+2I+DKwep6YBoVL9L81gRYRycqg+w+cTZ1TF
    /s6NC5YRKSeOCrLw3ombhjyyuPl8T/h9cpXt6m3y2xIVLYVzeDhaql3hdi6IpRh6
    rwkMhJ/XmOpbDinXb1fWdFOyQwqsXQWOEwKBYIkM6cPnuid7qwaxfP22hDgAolGM
    LY7TPKUPRwV+a5Y3VPl7h0YSK7lDyckTJdtBqI6d4PWQLnHakUgRQy69nZhGRtUt
    PMSJ7I4Qtt3B6AwDq+SJTggwtJQHeid0jPki6pouenhPQ6dZT532x16XD+WIcD2f
    //XzzOueS29KB7lt/wH5K6EuxwIDAQABo3YwdDAdBgNVHQ4EFgQUDY6XJ/FIRFX3
    dB4Wep3RVM84RXowDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBQNjpcn8UhE
    Vfd0HhZ6ndFUzzhFejARBgNVHSAECjAIMAYGBCoDBAUwDgYDVR0PAQH/BAQDAgEG
    MA0GCSqGSIb3DQEBDQUAA4ICAQA5s59/Olio4svHXiKu7sPQRvrf4GfGB7hUjBGk
    YW2YOHTYnHavSqlBASHc8gGGwuc7v7+H+vmOfSLZfGDqxnBqeJx1H5E0YqEXtNqW
    G1JusIFa9xWypcONjg9v7IMnxxQzLYws4YwgPychpMzWY6B5hZsjUyKgB+1igxnf
    uaBueLPw3ZaJhcCL8gz6SdCKmQpX4VaAadS0vdMrBOmd826H+aDGZek1vMjuH11F
    fJoXY2jyDnlol7Z4BfHc011toWNMxojI7w+U4KKCbSxpWFVYITZ8WlYHcj+b2A1+
    dFQZFzQN+Y1Wx3VIUqSks6P7F5aF/l4RBngy08zkP7iLA/C7rm61xWxTmpj3p6SG
    fUBsrsBvBgfJQHD/Mx8U3iQCa0Vj1XPogE/PXQQq2vyWiAP662hD6og1/om3l1PJ
    TBUyYXxqJO75ux8IWblUwAjsmTlF/Pcj8QbcMPXLMTgNQAgarV6guchjivYqb6Zr
    hq+Nh3JrF0HYQuMgExQ6VX8T56saOEtmlp6LSQi4HvKatCNfWUJGoYeT5SrcJ6sn
    By7XLMhQUCOXcBwKbNvX6aP79VA3yeJHZO7XParX7V9BB+jtf4tz/usmAT/+qXtH
    CCv9Xf4lv8jgdOnFfXbXuT8I4gz8uq8ElBlpbJntO6p/NY5a08E6C7FWVR+WJ5vZ
    OP2HsA==
    -----END CERTIFICATE-----
